# Site metadata
title = "Space Cubics"
base_url = "https://spacecubics.com"
description = "Site built using Zola and the Duckquill Theme."
author = "EO"

# Build settings
compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
default_language = "en"

# Taxonomies
taxonomies = [
  { name = "tags", feed = true }
]

# Markdown settings
[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" }
]
smart_punctuation = true
bottom_footnotes = true

# Search settings
[search]
index_format = "fuse_json"

# Multilingual settings
[languages.fr]
title = "Duckquill"
description = "Un thème affirmé, moderne, beau et clair pour Zola."
generate_feeds = true
taxonomies = [
  { name = "tags", feed = true }
]

# Theme and UI extras
[extra]
default_theme = "dark"
accent_color = "#ff7800"
accent_color_dark = "#ffa348"
show_copy_button = true
show_reading_time = true
show_share_button = true
show_backlinks = true

# Content Security Policy (CSP)
csp = [
  { directive = "font-src", domains = ["'self'"] },
  { directive = "img-src", domains = ["'self'", "https:", "data:"] },
  { directive = "media-src", domains = ["'self'", "https:"] },
  { directive = "script-src", domains = ["'self'"] },
  { directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
  { directive = "frame-src", domains = ["https://player.vimeo.com", "https://www.youtube-nocookie.com", "https://toot.community"] },
  { directive = "connect-src", domains = ["https://toot.community"] },
  { directive = "base-uri", domains = ["'none'"] },
  { directive = "form-action", domains = ["'none'"] }
]

# Navigation links
[extra.nav]
show_theme_switcher = true
links = [
  { url = "@/about_us/_index.md", name = "About us" },
  { url = "@/products/_index.md", name = "Products" },
  { url = "@/news/_index.md", name = "News" },
  { url = "@/recruit/_index.md", name = "Recruit" }
]

# Footer socials
[extra.footer]
socials = [
  { url = "https://github.com/spacecubics", name = "GitHub", icon = "..." },
  { url = "https://www.linkedin.com/company/spacecubics", name = "Linkedin", icon = "..." },
  { url = "https://www.youtube.com/channel/UCcTXF6z-D5B2xkDamlPzSzg", name = "YouTube", icon = "..." },
  { url = "https://x.com/SpaceCubics", name = "X", icon = "..." }
]
show_source = false

# Comments settings
[extra.comments]
host = "vmst.io"
user = "daudix"
show_qr = true

# GoatCounter analytics
[extra.goatcounter]
user = "duckquill"
# Uncomment and set if using custom host:
# host = "YOUR_SERVER"

# Debug settings
[extra.debug]
layout = false
no_styles = false
