[build]
publish = "public"
command = "curl -LO https://github.com/getzola/zola/releases/download/v0.22.2/zola-v0.22.2-x86_64-unknown-linux-gnu.tar.gz && tar -xzf zola-v0.22.2-x86_64-unknown-linux-gnu.tar.gz && ./zola build"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.18.0"
